// scripts/build-runtime.mjs
//
// Build the ONE artifact the shell consumes: `dist/naby-runtime.mjs`.
//
// WHY A BUNDLE, and not a `file:` dependency or a tsconfig path alias:
//
//   The shell (shell/, a git submodule) pins `ai@6`; we pin `ai@7`. Both trees
//   are installed. Any linkage that leaves a bare `import ... from 'ai'` in the
//   code the shell loads is a coin flip over which major resolves — npm cannot
//   even nest a second `ai` under a linked local package, so a `file:..`
//   dependency would force one version on both. Bundling removes the question:
//   esbuild resolves every bare import HERE, in the parent tree, against our
//   pinned ai@7, and inlines the result. The emitted file imports nothing but
//   node builtins, so the shell's node_modules never gets a vote.
//
//   It also makes the shell-side linkage free: naby.ts imports this artifact by
//   relative path. No `file:` dep, no package-lock churn, no tsconfig `paths`,
//   no `transpilePackages` entry — i.e. no shell config diff at all, which is
//   what keeps the fork merge-friendly.
//
// Types travel alongside: `tsc -p tsconfig.build.json` emits the declaration
// tree into dist/types/, and dist/naby-runtime.d.mts re-exports its root so the
// shell (strict mode) sees real types for the bundle, not `any`.

import { build } from 'esbuild';
import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outfile = resolve(root, 'dist/naby-runtime.mjs');

mkdirSync(resolve(root, 'dist'), { recursive: true });

// -- 1. the runtime bundle -------------------------------------------------
const result = await build({
  entryPoints: [resolve(root, 'src/runtime-entry.ts')],
  outfile,
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: 'node20',
  // platform:'node' already externalizes node builtins. Everything else —
  // ai@7, the five @ai-sdk/* adapters, zod — is deliberately INLINED.
  external: [],
  // A few transitive CJS modules (anthropic/bedrock token+auth-config IO) call
  // `require('fs' | 'path' | 'os')` from inside lazy wrappers. esbuild's ESM
  // output routes those through a `__require` shim that THROWS unless a real
  // `require` is in scope, so those paths would only blow up once someone hit
  // them at runtime. Define one from import.meta.url — the standard esbuild
  // ESM-on-node recipe — so the shim finds it.
  banner: {
    js:
      "import { createRequire as __nabyCreateRequire } from 'node:module';\n" +
      'const require = __nabyCreateRequire(import.meta.url);',
  },
  sourcemap: false,
  legalComments: 'none',
  logLevel: 'warning',
  metafile: true,
});

// -- 2. declarations -------------------------------------------------------
execFileSync(
  process.execPath,
  [resolve(root, 'node_modules/typescript/bin/tsc'), '-p', resolve(root, 'tsconfig.build.json')],
  { cwd: root, stdio: 'inherit' },
);

writeFileSync(
  resolve(root, 'dist/naby-runtime.d.mts'),
  '// Generated by scripts/build-runtime.mjs — types for dist/naby-runtime.mjs.\n' +
    "export * from './types/runtime-entry.js';\n",
);

const bytes = Object.values(result.metafile.outputs)[0]?.bytes ?? 0;
console.log(
  `naby-runtime: dist/naby-runtime.mjs (${(bytes / 1024).toFixed(0)} KB, self-contained) + dist/naby-runtime.d.mts`,
);
